### ISSUE TITLE
`val` does not live long enough 에러 

### ISSUE THREAD

**Issue by why-arong** [kookmin-university-2023-rust-team-D/rust-project#1]
https://github.com/kookmin-university-2023-rust-team-D/rust-project/blob/40a4f1662b4e7aa8a2ade87f4035d7523130fb78/loader.rs#L29

let status_str = match line {
    Ok(val) => val,
    Err(_err) => panic!("파일을 읽을 수 없습니다!"),
};

let mut status = status_str.split_whitespace().map(|s| s);
제 파일에서는 이 라인에서 에러가 생겨서
위와 같이 수정했습니다.
val lifetime관련 문제가 생겼어요

**Comment by kimdonguk-kmu** [comment]
제 파일하고 합치면 그런 오류가 나는 것 같아요.
impl Player와 Monster를 없애셔야 할 것 같습니다.
